// Build 14: Export Markdown Report
// GET /api/export?app_id=...

const { getSupabase } = require('./lib/supabase');
const { ok, badRequest, serverError } = require('./lib/respond');

module.exports = async (req, res) => {
  if (req.method !== 'GET') return badRequest(res, 'GET only');

  try {
    const { app_id } = req.query || {};
    if (!app_id) return badRequest(res, 'app_id required');

    const supabase = getSupabase();

    const [appRes, snapshotRes, creativesRes] = await Promise.all([
      supabase.from('watchlist_apps').select('*').eq('id', app_id).single(),
      supabase.from('latest_snapshots').select('*').eq('app_id', app_id).single(),
      supabase.from('creatives').select('*').eq('app_id', app_id),
    ]);

    const app = appRes.data;
    const snapshot = snapshotRes.data;
    const creatives = creativesRes.data || [];

    if (!app) return badRequest(res, 'App not found');

    const totalC = creatives.length;
    const activeC = creatives.filter(c => c.status === 'active' || c.status === 'scaling').length;
    const decayC = creatives.filter(c => c.status === 'decay').length;

    const md = `# Weekly Ad Intelligence Report
**App:** ${app.app_name}
**Publisher:** ${app.publisher || '—'}
**Platform:** ${app.platform || '—'}
**Date:** ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
**Last Synced:** ${app.last_synced_at ? new Date(app.last_synced_at).toLocaleDateString() : 'Never'}

## Key Metrics
| Metric | Value |
|--------|-------|
| CHI | ${snapshot?.chi_score || '—'} |
| CREI | ${snapshot?.crei_score || '—'} |
| Total Downloads | ${snapshot?.downloads ? (snapshot.downloads / 1000).toFixed(1) + 'K' : '—'} |
| Revenue | ${snapshot?.revenue_cents ? '$' + (snapshot.revenue_cents / 100 / 1000).toFixed(1) + 'K' : '—'} |
| Active Creatives | ${activeC} / ${totalC} |
| Networks | ${snapshot?.networks_count || '—'} |
| Primary Network | ${snapshot?.primary_network || '—'} |

## Creative Breakdown
| Stage | Count | % |
|-------|-------|---|
| Active | ${activeC} | ${totalC > 0 ? Math.round(activeC / totalC * 100) : 0}% |
| Testing | ${creatives.filter(c => c.status === 'testing').length} | ${totalC > 0 ? Math.round(creatives.filter(c => c.status === 'testing').length / totalC * 100) : 0}% |
| Scaling | ${creatives.filter(c => c.status === 'scaling').length} | ${totalC > 0 ? Math.round(creatives.filter(c => c.status === 'scaling').length / totalC * 100) : 0}% |
| Decay | ${decayC} | ${totalC > 0 ? Math.round(decayC / totalC * 100) : 0}% |

## Summary
${snapshot?.chi_score < 50 ? '⚠️ Creative health needs attention (CHI ' + snapshot.chi_score + ')' : '✅ Creative pipeline healthy (CHI ' + (snapshot?.chi_score || '—') + ')'}
${decayC > totalC * 0.3 ? '⚠️ High decay rate: ' + decayC + ' creatives (' + Math.round(decayC / totalC * 100) + '%) — audit recommended' : ''}
${snapshot?.networks_count <= 1 ? '⚠️ Single network dependency — diversification recommended' : '✅ ' + snapshot?.networks_count + ' networks active'}

---
*Generated by ZPS Ad Intelligence Tool*
`;

    return ok(res, { markdown: md, app_name: app.app_name });
  } catch (err) {
    console.error('Export error:', err);
    return serverError(res, err.message);
  }
};
